### ISSUE TITLE
Support easy Camunda Cloud configuration

### ISSUE THREAD

**Issue by ArtunSubasi** [zeebe-io/spring-zeebe#81]
The latest version 0.7.1 doesn't seem to support Camunda Cloud out of the box. According to the readme, it is only possible to configure `zeebe.client.broker.contactPoint`. The configuration of a client id and a client secret is not possible.

The #67 should make it possible to add a credentials provider. Nevertheless, it would nice to support Camunda Cloud with less effort. For example:

```yaml
zeebe:
  client:
    broker:
      contactPoint: "Camunda Cloud Contact Point"
    id: "Camunda Cloud Client ID"
    secret: "Camunda Cloud Client Secret"
```
