### ISSUE TITLE
The job type and worker name are read from the wrong config  

### ISSUE THREAD

**Issue by saig0** [zeebe-io/spring-zeebe#90]
## Problem

When I implement a job worker using `@ZeebeWorker` then the default job type and worker name are read from the wrong configuration. The default values of the annotation point to a path that is different from the configuration.

```
public @interface ZeebeWorker {
  String type() default "${zeebe.worker.defaultType}";
  String name() default "${zeebe.worker.defaultName}";
```

So, the configuration must have:

```
zeebe:
  worker:
    defaultName: worker-name
    defaultType: job-type
```

But according to `ZeebeClientConfigurationProperties`, the configuration should be:

```
zeebe:
  client:
    worker:
      defaultName: worker-name
      defaultType: job-type
```

## Solution

Align the default values of the annotation with the configuration.

Note that this is a breaking change :warning:
